version: '2'
services:
  # web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - /opt/wwwroot:/usr/share/nginx/html
      # nginx configs
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nginx/conf.d/:/etc/nginx/conf.d/:ro
    links:
      - fpm:__DOCKER_PHP_FPM__

  # php-fpm
  fpm:
    build: ./php-fpm
    ports:
      - "9000"
    volumes:
      - /opt/wwwroot:/usr/share/nginx/html
    links:
      - mysql:mysql

  # database
  mysql:
    image: mariadb:10.9.4
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - /opt/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
